# Generated by Django 2.0.6 on 2018-08-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.CharField(max_length=200)),
                ('altura', models.CharField(max_length=200)),
                ('nacionalidade', models.CharField(max_length=200)),
                ('image', models.ImageField(max_length=254, upload_to='photos')),
            ],
        ),
    ]
