# Generated by Django 2.0 on 2018-05-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('suite', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=70)),
                ('phone', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
